/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Acceuil (void)
{
  GtkWidget *Acceuil;
  GtkWidget *fixed1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;

  Acceuil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Acceuil, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (Acceuil), _("acceuil"));
  gtk_window_set_position (GTK_WINDOW (Acceuil), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (Acceuil), FALSE);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Acceuil), fixed1);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 400, 336);
  gtk_widget_set_size_request (button1, 168, 72);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Gestion des voitures"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_AcceuilgestionVoiture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Acceuil, Acceuil, "Acceuil");
  GLADE_HOOKUP_OBJECT (Acceuil, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Acceuil, button1, "button1");
  GLADE_HOOKUP_OBJECT (Acceuil, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Acceuil, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Acceuil, image1, "image1");
  GLADE_HOOKUP_OBJECT (Acceuil, label1, "label1");

  return Acceuil;
}

GtkWidget*
create_gestion_voiture (void)
{
  GtkWidget *gestion_voiture;
  GtkWidget *fixed2;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *calendar1;
  GtkWidget *calendar2;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label17;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label18;
  GtkWidget *label4;
  GtkWidget *label63;
  GtkWidget *combobox7;
  GtkWidget *label9;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label64;
  GtkWidget *label19;
  GtkWidget *fixed4;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label20;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label29;
  GtkWidget *label32;
  GtkWidget *label34;
  GtkWidget *fixed5;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label28;
  GtkWidget *label30;
  GtkWidget *button7;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label68;
  GtkWidget *label65;
  GtkWidget *combobox8;
  GtkWidget *label27;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label33;
  GtkWidget *label62;

  gestion_voiture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_voiture, 1000, 700);
  gtk_window_set_title (GTK_WINDOW (gestion_voiture), _("Gestion Voitures"));
  gtk_window_set_position (GTK_WINDOW (gestion_voiture), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (gestion_voiture), FALSE);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_voiture), fixed2);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 16, 640);
  gtk_widget_set_size_request (button2, 96, 53);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 888, 640);
  gtk_widget_set_size_request (button3, 96, 53);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed2), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1008, 640);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 264, 104);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar1, 240, 248);
  gtk_widget_set_size_request (calendar1, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed3), calendar2, 712, 248);
  gtk_widget_set_size_request (calendar2, 236, 184);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  spinbutton2_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2, 256, 472);
  gtk_widget_set_size_request (spinbutton2, 56, 27);

  label17 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed3), label17, 64, 456);
  gtk_widget_set_size_request (label17, 128, 56);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed3), button4, 368, 552);
  gtk_widget_set_size_request (button4, 96, 53);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox4), label18, FALSE, FALSE, 0);

  label4 = gtk_label_new (_("Matricule : "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 88, 96);
  gtk_widget_set_size_request (label4, 80, 48);

  label63 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed3), label63, 88, 160);
  gtk_widget_set_size_request (label63, 80, 48);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox7, 264, 168);
  gtk_widget_set_size_request (combobox7, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Audi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Chevrolet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("Citroen"));

  label9 = gtk_label_new (_("<span foreground=\"blue\"><i>Voirure ajout\303\251 avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 40, 0);
  gtk_widget_set_size_request (label9, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  label6 = gtk_label_new (_("Date de disponiblit\303\251 : "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 64, 296);
  gtk_widget_set_size_request (label6, 128, 48);

  label7 = gtk_label_new (_("jusqu'a : "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 544, 296);
  gtk_widget_set_size_request (label7, 128, 48);

  label10 = gtk_label_new (_("<span foreground=\"red\"><b>Voiture existe d\303\251ja !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 320, 0);
  gtk_widget_set_size_request (label10, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label11 = gtk_label_new (_("<span foreground=\"red\"><b>Matricule est necessaire!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 448, 80);
  gtk_widget_set_size_request (label11, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label64 = gtk_label_new (_("<span foreground=\"red\"><b>Marque est necessaire!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed3), label64, 440, 152);
  gtk_widget_set_size_request (label64, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label19 = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label19);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label19);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed4), scrolledwindow1, 100, 88);
  gtk_widget_set_size_request (scrolledwindow1, 584, 384);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);
  gtk_widget_set_size_request (treeview1, 584, 384);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 208, 504);
  gtk_widget_set_size_request (button5, 104, 56);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed4), button6, 336, 504);
  gtk_widget_set_size_request (button6, 104, 56);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox6), label29, FALSE, FALSE, 0);

  label32 = gtk_label_new (_("<span foreground=\"red\"><b>faites une selection !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 240, 16);
  gtk_widget_set_size_request (label32, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  label34 = gtk_label_new (_("Afficher/Supprimer"));
  gtk_widget_show (label34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label34);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed5), entry2, 352, 232);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 352, 304);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 200, 1200, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton4, 392, 376);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label28 = gtk_label_new (_("Modifier le Voiture : "));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 200, 72);
  gtk_widget_set_size_request (label28, 152, 48);

  label30 = gtk_label_new ("");
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 384, 72);
  gtk_widget_set_size_request (label30, 104, 48);

  button7 = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 352, 496);
  gtk_widget_set_size_request (button7, 96, 53);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button7), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox7), label68, FALSE, FALSE, 0);

  label65 = gtk_label_new (_("Marque : "));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed5), label65, 224, 160);
  gtk_widget_set_size_request (label65, 128, 48);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox8, 352, 160);
  gtk_widget_set_size_request (combobox8, 160, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("BMW"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Audi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Chevrolet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("Citroen"));

  label27 = gtk_label_new (_("Prix : "));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 200, 368);
  gtk_widget_set_size_request (label27, 128, 48);

  label24 = gtk_label_new (_("Date de disponibilit\303\251 : "));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 200, 224);
  gtk_widget_set_size_request (label24, 128, 48);

  label25 = gtk_label_new (_("jusqu'a : "));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 208, 296);
  gtk_widget_set_size_request (label25, 128, 48);

  label33 = gtk_label_new (_("<span foreground=\"blue\"><i>Modification faite avec succ\303\251s</i></span>"));
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 312, 0);
  gtk_widget_set_size_request (label33, 256, 72);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label62 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label62);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label62);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_gestionAcceuil_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_Ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_Supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_Modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_ConfirmerModification_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_voiture, gestion_voiture, "gestion_voiture");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button2, "button2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button3, "button3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button4, "button4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label63, "label63");
  GLADE_HOOKUP_OBJECT (gestion_voiture, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label10, "label10");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label11, "label11");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label64, "label64");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label29, "label29");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label32, "label32");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label34, "label34");
  GLADE_HOOKUP_OBJECT (gestion_voiture, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (gestion_voiture, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (gestion_voiture, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label30, "label30");
  GLADE_HOOKUP_OBJECT (gestion_voiture, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label68, "label68");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label65, "label65");
  GLADE_HOOKUP_OBJECT (gestion_voiture, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label27, "label27");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label25, "label25");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label33, "label33");
  GLADE_HOOKUP_OBJECT (gestion_voiture, label62, "label62");

  return gestion_voiture;
}

